// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlXhKNNpXx7A3CaiJq9Z6zJGqWSA3nYTU',
    appId: '1:952517685091:web:c4dc9cff027c67a0caad56',
    messagingSenderId: '952517685091',
    projectId: 'aluminithub',
    authDomain: 'aluminithub.firebaseapp.com',
    storageBucket: 'aluminithub.appspot.com',
    measurementId: 'G-W5P0G6DSQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVqhIIt18V35ZGmMee5v4O7f2pZvzkhI4',
    appId: '1:952517685091:android:37aa232c0819efe5caad56',
    messagingSenderId: '952517685091',
    projectId: 'aluminithub',
    storageBucket: 'aluminithub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE-VRaEpW6VrMSidhQ4bHaRtzwG_O1ecA',
    appId: '1:952517685091:ios:124a455106436366caad56',
    messagingSenderId: '952517685091',
    projectId: 'aluminithub',
    storageBucket: 'aluminithub.appspot.com',
    iosBundleId: 'com.example.alumni',
  );
}
